---
- name: Install fzf
  ansible.builtin.include_tasks: tools/fzf.yaml

#- name: Install terraform
#  ansible.builtin.include_tasks: tools/terraform.yaml

- name: Install k9s
  ansible.builtin.include_tasks: tools/k9s.yaml

- name: Install lazygit
  ansible.builtin.include_tasks: tools/lazygit.yaml

- name: Install Visual Studio Code
  ansible.builtin.include_tasks: tools/vscode.yaml

#- name: Install lazyssh
#  ansible.builtin.include_tasks: tools/lazyssh.yaml
