---
- name: Add Copr repository for k9s
  ansible.builtin.command:
    cmd: dnf copr enable -y luminoso/k9s
  become: true
  changed_when: true

- name: Install k9s
  ansible.builtin.dnf:
    name: k9s
    state: present
  become: true
